= Buddy - Security library for clojure.
Andrey Antukh, <niwi@niwi.be>
:toc: left
:numbered:
:source-highlighter: pygments
:pygments-style: friendly
:sectlinks:

== Introduction

_buddy_ is a complete security library for clojure.

Since version 0.3.0, buddy is splitted in four modules for improve modularity
of the application and allow to people include only wanted parts of buddy
instead of one monolitic library.

Each module has it own functionality and its own documentation. This document/page
only serves as introduction to the library and the content of index.

Below are the details and features of each module.


== Install

The recommended way is setup only modules that you need, and for concrete
install instructions, see the module documentation.

But if you want to emulate the previos behavior, you can include all them:

[source,clojure]
----
[buddy/buddy-core "x.y.z"]
[buddy/buddy-sign "x.y.z"]
[buddy/buddy-hashers "x.y.z"]
[buddy/buddy-auth "x.y.z"]
----


== Get the Source

_buddy_ is open source and can be found on link:https://github.com/funcool[github]
organization.

You can clone the public repository with this command:

[source,text]
----
git clone https://github.com/funcool/buddy-core
git clone https://github.com/funcool/buddy-sign
git clone https://github.com/funcool/buddy-hashers
git clone https://github.com/funcool/buddy-auth
----


== Modules Summary

=== buddy-core

Cryptographyc api.

With that list of features:

- secure hash functions (digest)
- signature & authentication (mac & digital signature)
- encryption (block & stream ciphers)
- key derivartion functions (kdf)

link:http://funcool.github.io/buddy-core/latest/[Documentation]


=== buddy-auth

Authentication and Authorization for ring and ring-based
web applications.

With that list of features:

- Authentication middlewares for ring.
- Authorization middleware for ring.
- Authentication/Authorization backends (token, http-basic, session).
- Access rules system.

link:http://funcool.github.io/buddy-auth/latest/[Documentation]


=== buddy-hashers

Secure password hashers.

With that list of features:

- A collection of secure password hashers (bcrypt, scrypt, pbkdf2, ...)

link:http://funcool.github.io/buddy-hashers/latest/[Documentation]


=== buddy-sign

High level message signing module.

With that list of features:

- Generic message signing (based on django's sign framework)
- Json Web Signature/Token

link:http://funcool.github.io/buddy-sign/latest/[Documentation]



== FAQ

*Buddy is a security library/framework?*

Yes and No. I don't like call "security" library because security represents a very generic
concepts and can contain a lot of things. Buddy targets cryptography, message signing
and authentication/authorization extensions for ring compatible web applications. You can see
the main target on the "Introduction" section of this documentation.

*How can I use _buddy_ with link:http://clojure-liberator.github.io/liberator/[liberator]?*

By design, _buddy_ has authorization and authentication well
separated. This helps a lot if you want use only one part of it (ex:
authentication only) without including the other.

The best combination is to use _buddy_'s authentication middleware
with liberator authorization endpoints.

*Buddy has own cryptographic algorithms implementations?*

Mainly no, I'm not cryptography expert and for this I rely on the to battle tested Bouncy Castle java
library that's dedicated to this purpose.

*Buddy will support pgp?*

Surely not! Because there already exists one good link:https://github.com/greglook/clj-pgp[library for that].

== How to Contribute?

=== Philosophy

Five most important rules:

- Beautiful is better than ugly.
- Explicit is better than implicit.
- Simple is better than complex.
- Complex is better than complicated.
- Readability counts.

All contributions to _buddy_ should keep these important rules in mind.


=== Procedure

Unlike Clojure and other Clojure contrib libs, _buddy_ does not have many
restrictions for contributions. Just follow the following steps depending on the
situation:

**Bugfix**:

- Fork the GitHub repo.
- Fix a bug/typo on a new branch.
- Make a pull-request to master.

**New feature**:

- Open new issues with the new feature proposal.
- If it is accepted, follow the same steps as "bugfix".


=== License

[source,text]
----
Copyright (c) 2013-2015, Andrey Antukh

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
----
