= Buddy - Password Hashers
Andrey Antukh, <niwi@niwi.be>
0.3.0-SNAPSHOT
:toc: left
:numbered:
:source-highlighter: pygments
:pygments-style: friendly
:sectlinks:

== Introduction

Buddy *hashers* module is dedicated to provide a collection
of password hashers functions.

.Supported password hashers algorithms
[options="header"]
|===========================================================================
| Hash algorithm name  | Namespace              | Observations
| Bcrypt               | `buddy.hashers.bcrypt` | Recommended
| Pbkdf2               | `buddy.hashers.pbkdf2` | Recommended
| Scrypt               | `buddy.hashers.scrypt` | Recommended
| sha256               | `buddy.hashers.sha256` | Not recommended
| md5                  | `buddy.hashers.md5`    | Broken! Not Recommended
|===========================================================================

A hasher consists in two functions: _make-password_ and _check-password_. The
purpose of these functions is obvious: creating a new password, and verifying
incoming plain text password with the previously created hash.

== BCrypt

.Example of creating and verifying a new hash
[source,clojure]
----
(require '[buddy.hashers.bcrypt :as hs])

(def myhash (hs/make-password "secretpassword"))
(def ok (hs/check-password "secretpassword" myhash))

;; ok var reference should contain true
----

NOTE: hasher functions, unlike cryptographic hash functions, expect strings instead
of bytes.

NOTE: _make-password_ function options may vary depending of hasher algorithm is used.
